version: '3'
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
       - mongodbdata:/data/db
       - ./etc/mongod.conf:/etc/mongo/mongod.conf
    ports:
      - '27017:27017'
    command: --config /etc/mongo/mongod.conf
  web:
    restart: always
    environment: 
      - APP_TYPE=chat
    build: .
    ports:
      - "3050:3050"
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongodbdata:
    external: false
