version: "3"
services: 
  mongo:
    container_name: realtime-app-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'
    environment: 
      - MONGO_INITDB_DATABASE=realtime-chat

  web:
    container_name: rt_app_chat
    restart: always
    environment: 
      - PORT=8060
      - APP_TYPE=chat
      - DB_HOST=mongo
    build: .
    ports:
      - "3050:3050"
    depends_on:
        - mongo

volumes: 
  mongo: